# Generated by Django 4.2.20 on 2025-04-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id_phones', models.AutoField(primary_key=True, serialize=False)),
                ('sip_phone', models.IntegerField()),
                ('external_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('id_employee_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('id_role_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id_employee_phone', models.AutoField(primary_key=True, serialize=False)),
                ('id_employee_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('id_phone_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id_bell', models.AutoField(primary_key=True, serialize=False)),
                ('call_reccording', models.CharField(max_length=200)),
                ('datetime_bell', models.DateTimeField()),
                ('client_phone', models.CharField(max_length=20)),
                ('call_duration', models.IntegerField()),
                ('text_transripct', models.TextField(blank=True, null=True)),
                ('vector', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('id_employee_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
        ),
    ]
