# Generated by Django 4.2.20 on 2025-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='external_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sip_phone',
            field=models.CharField(max_length=30),
        ),
    ]
